fix for not always failing

diff --git a/scripts/testing/ats.sh.in b/scripts/testing/ats.sh.in
--- a/scripts/testing/ats.sh.in
+++ b/scripts/testing/ats.sh.in
@@ -102,5 +102,6 @@ if [ $? -ne 0 ]; then { echo "ERROR: Failed Integration tests, aborting."; exit 
 # Work around because ATS is currently not returning an error code on failed tests
 # Get log dir that was just created by ATS
 ATS_LOG_DIR=`ls -1d $SYS_TYPE*.logs | sort -r | head -n1`
-find . -path $ATS_LOG_DIR/atsr.xml | grep -q FAIL
-if [ $? -ne 0 ]; then { echo "ERROR: Failed Integration tests, aborting."; exit 1; } fi
+# grep returns 0 on finding a line that matches, which is a failure in this case
+grep -q FAIL $ATS_LOG_DIR/atsr.xml
+if [ $? -eq 0 ]; then { echo "ERROR: Failed Integration tests, aborting."; exit 1; } fi
